# Generated by Django 4.1.5 on 2023-01-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myadd1_title', models.CharField(max_length=50)),
                ('myadd1_data', models.DateTimeField(verbose_name='post_images/')),
                ('myadd1_text', models.CharField(max_length=300)),
                ('myadd1_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
