# Generated by Django 4.1.5 on 2023-01-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300)),
                ('post_data', models.DateTimeField()),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(upload_to='post_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
